// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-orderer/common/configrulesverifier"
)

type FakeConfigRolesVerifier struct {
	ValidateNewConfigStub        func(*common.Envelope) error
	validateNewConfigMutex       sync.RWMutex
	validateNewConfigArgsForCall []struct {
		arg1 *common.Envelope
	}
	validateNewConfigReturns struct {
		result1 error
	}
	validateNewConfigReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigRolesVerifier) ValidateNewConfig(arg1 *common.Envelope) error {
	fake.validateNewConfigMutex.Lock()
	ret, specificReturn := fake.validateNewConfigReturnsOnCall[len(fake.validateNewConfigArgsForCall)]
	fake.validateNewConfigArgsForCall = append(fake.validateNewConfigArgsForCall, struct {
		arg1 *common.Envelope
	}{arg1})
	stub := fake.ValidateNewConfigStub
	fakeReturns := fake.validateNewConfigReturns
	fake.recordInvocation("ValidateNewConfig", []interface{}{arg1})
	fake.validateNewConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigRolesVerifier) ValidateNewConfigCallCount() int {
	fake.validateNewConfigMutex.RLock()
	defer fake.validateNewConfigMutex.RUnlock()
	return len(fake.validateNewConfigArgsForCall)
}

func (fake *FakeConfigRolesVerifier) ValidateNewConfigCalls(stub func(*common.Envelope) error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = stub
}

func (fake *FakeConfigRolesVerifier) ValidateNewConfigArgsForCall(i int) *common.Envelope {
	fake.validateNewConfigMutex.RLock()
	defer fake.validateNewConfigMutex.RUnlock()
	argsForCall := fake.validateNewConfigArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConfigRolesVerifier) ValidateNewConfigReturns(result1 error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = nil
	fake.validateNewConfigReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfigRolesVerifier) ValidateNewConfigReturnsOnCall(i int, result1 error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = nil
	if fake.validateNewConfigReturnsOnCall == nil {
		fake.validateNewConfigReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateNewConfigReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfigRolesVerifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigRolesVerifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ configrulesverifier.ConfigRolesVerifier = new(FakeConfigRolesVerifier)
