// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/node/assembler"
)

type FakeAssemblerRestarter struct {
	SoftStopStub        func()
	softStopMutex       sync.RWMutex
	softStopArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAssemblerRestarter) SoftStop() {
	fake.softStopMutex.Lock()
	fake.softStopArgsForCall = append(fake.softStopArgsForCall, struct {
	}{})
	stub := fake.SoftStopStub
	fake.recordInvocation("SoftStop", []interface{}{})
	fake.softStopMutex.Unlock()
	if stub != nil {
		fake.SoftStopStub()
	}
}

func (fake *FakeAssemblerRestarter) SoftStopCallCount() int {
	fake.softStopMutex.RLock()
	defer fake.softStopMutex.RUnlock()
	return len(fake.softStopArgsForCall)
}

func (fake *FakeAssemblerRestarter) SoftStopCalls(stub func()) {
	fake.softStopMutex.Lock()
	defer fake.softStopMutex.Unlock()
	fake.SoftStopStub = stub
}

func (fake *FakeAssemblerRestarter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAssemblerRestarter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ assembler.AssemblerRestarter = new(FakeAssemblerRestarter)
