// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"arma/common/types"
	"arma/node/assembler"
	"sync"
)

type FakeBatchCacheFactory struct {
	CreateStub        func(types.ShardID, types.PartyID) *assembler.BatchCache
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 types.ShardID
		arg2 types.PartyID
	}
	createReturns struct {
		result1 *assembler.BatchCache
	}
	createReturnsOnCall map[int]struct {
		result1 *assembler.BatchCache
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchCacheFactory) Create(arg1 types.ShardID, arg2 types.PartyID) *assembler.BatchCache {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 types.ShardID
		arg2 types.PartyID
	}{arg1, arg2})
	fake.recordInvocation("Create", []interface{}{arg1, arg2})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.createReturns
	return fakeReturns.result1
}

func (fake *FakeBatchCacheFactory) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeBatchCacheFactory) CreateCalls(stub func(types.ShardID, types.PartyID) *assembler.BatchCache) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeBatchCacheFactory) CreateArgsForCall(i int) (types.ShardID, types.PartyID) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBatchCacheFactory) CreateReturns(result1 *assembler.BatchCache) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 *assembler.BatchCache
	}{result1}
}

func (fake *FakeBatchCacheFactory) CreateReturnsOnCall(i int, result1 *assembler.BatchCache) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 *assembler.BatchCache
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 *assembler.BatchCache
	}{result1}
}

func (fake *FakeBatchCacheFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchCacheFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ assembler.BatchCacheFactory = new(FakeBatchCacheFactory)
