// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/common/types"
	"github.com/hyperledger/fabric-x-orderer/node/assembler"
	"github.com/hyperledger/fabric-x-orderer/node/config"
)

type FakeBatchBringerFactory struct {
	CreateStub        func(map[types.ShardID]map[types.PartyID]types.BatchSequence, *config.AssemblerNodeConfig, types.Logger) assembler.BatchBringer
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 map[types.ShardID]map[types.PartyID]types.BatchSequence
		arg2 *config.AssemblerNodeConfig
		arg3 types.Logger
	}
	createReturns struct {
		result1 assembler.BatchBringer
	}
	createReturnsOnCall map[int]struct {
		result1 assembler.BatchBringer
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchBringerFactory) Create(arg1 map[types.ShardID]map[types.PartyID]types.BatchSequence, arg2 *config.AssemblerNodeConfig, arg3 types.Logger) assembler.BatchBringer {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 map[types.ShardID]map[types.PartyID]types.BatchSequence
		arg2 *config.AssemblerNodeConfig
		arg3 types.Logger
	}{arg1, arg2, arg3})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2, arg3})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchBringerFactory) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeBatchBringerFactory) CreateCalls(stub func(map[types.ShardID]map[types.PartyID]types.BatchSequence, *config.AssemblerNodeConfig, types.Logger) assembler.BatchBringer) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeBatchBringerFactory) CreateArgsForCall(i int) (map[types.ShardID]map[types.PartyID]types.BatchSequence, *config.AssemblerNodeConfig, types.Logger) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBatchBringerFactory) CreateReturns(result1 assembler.BatchBringer) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 assembler.BatchBringer
	}{result1}
}

func (fake *FakeBatchBringerFactory) CreateReturnsOnCall(i int, result1 assembler.BatchBringer) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 assembler.BatchBringer
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 assembler.BatchBringer
	}{result1}
}

func (fake *FakeBatchBringerFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchBringerFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ assembler.BatchBringerFactory = new(FakeBatchBringerFactory)
