// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-orderer/node/assembler"
)

type FakeConfigProcessor struct {
	ConfigBlockNumberStub        func() uint64
	configBlockNumberMutex       sync.RWMutex
	configBlockNumberArgsForCall []struct {
	}
	configBlockNumberReturns struct {
		result1 uint64
	}
	configBlockNumberReturnsOnCall map[int]struct {
		result1 uint64
	}
	ProcessNewConfigBlockStub        func(*common.Block)
	processNewConfigBlockMutex       sync.RWMutex
	processNewConfigBlockArgsForCall []struct {
		arg1 *common.Block
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigProcessor) ConfigBlockNumber() uint64 {
	fake.configBlockNumberMutex.Lock()
	ret, specificReturn := fake.configBlockNumberReturnsOnCall[len(fake.configBlockNumberArgsForCall)]
	fake.configBlockNumberArgsForCall = append(fake.configBlockNumberArgsForCall, struct {
	}{})
	stub := fake.ConfigBlockNumberStub
	fakeReturns := fake.configBlockNumberReturns
	fake.recordInvocation("ConfigBlockNumber", []interface{}{})
	fake.configBlockNumberMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigProcessor) ConfigBlockNumberCallCount() int {
	fake.configBlockNumberMutex.RLock()
	defer fake.configBlockNumberMutex.RUnlock()
	return len(fake.configBlockNumberArgsForCall)
}

func (fake *FakeConfigProcessor) ConfigBlockNumberCalls(stub func() uint64) {
	fake.configBlockNumberMutex.Lock()
	defer fake.configBlockNumberMutex.Unlock()
	fake.ConfigBlockNumberStub = stub
}

func (fake *FakeConfigProcessor) ConfigBlockNumberReturns(result1 uint64) {
	fake.configBlockNumberMutex.Lock()
	defer fake.configBlockNumberMutex.Unlock()
	fake.ConfigBlockNumberStub = nil
	fake.configBlockNumberReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeConfigProcessor) ConfigBlockNumberReturnsOnCall(i int, result1 uint64) {
	fake.configBlockNumberMutex.Lock()
	defer fake.configBlockNumberMutex.Unlock()
	fake.ConfigBlockNumberStub = nil
	if fake.configBlockNumberReturnsOnCall == nil {
		fake.configBlockNumberReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.configBlockNumberReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeConfigProcessor) ProcessNewConfigBlock(arg1 *common.Block) {
	fake.processNewConfigBlockMutex.Lock()
	fake.processNewConfigBlockArgsForCall = append(fake.processNewConfigBlockArgsForCall, struct {
		arg1 *common.Block
	}{arg1})
	stub := fake.ProcessNewConfigBlockStub
	fake.recordInvocation("ProcessNewConfigBlock", []interface{}{arg1})
	fake.processNewConfigBlockMutex.Unlock()
	if stub != nil {
		fake.ProcessNewConfigBlockStub(arg1)
	}
}

func (fake *FakeConfigProcessor) ProcessNewConfigBlockCallCount() int {
	fake.processNewConfigBlockMutex.RLock()
	defer fake.processNewConfigBlockMutex.RUnlock()
	return len(fake.processNewConfigBlockArgsForCall)
}

func (fake *FakeConfigProcessor) ProcessNewConfigBlockCalls(stub func(*common.Block)) {
	fake.processNewConfigBlockMutex.Lock()
	defer fake.processNewConfigBlockMutex.Unlock()
	fake.ProcessNewConfigBlockStub = stub
}

func (fake *FakeConfigProcessor) ProcessNewConfigBlockArgsForCall(i int) *common.Block {
	fake.processNewConfigBlockMutex.RLock()
	defer fake.processNewConfigBlockMutex.RUnlock()
	argsForCall := fake.processNewConfigBlockArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConfigProcessor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigProcessor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ assembler.ConfigProcessor = new(FakeConfigProcessor)
