// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/common/requestfilter"
)

type FakeFilterConfig struct {
	GetClientSignatureVerificationRequiredStub        func() bool
	getClientSignatureVerificationRequiredMutex       sync.RWMutex
	getClientSignatureVerificationRequiredArgsForCall []struct {
	}
	getClientSignatureVerificationRequiredReturns struct {
		result1 bool
	}
	getClientSignatureVerificationRequiredReturnsOnCall map[int]struct {
		result1 bool
	}
	GetRequestMaxBytesStub        func() uint64
	getRequestMaxBytesMutex       sync.RWMutex
	getRequestMaxBytesArgsForCall []struct {
	}
	getRequestMaxBytesReturns struct {
		result1 uint64
	}
	getRequestMaxBytesReturnsOnCall map[int]struct {
		result1 uint64
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFilterConfig) GetClientSignatureVerificationRequired() bool {
	fake.getClientSignatureVerificationRequiredMutex.Lock()
	ret, specificReturn := fake.getClientSignatureVerificationRequiredReturnsOnCall[len(fake.getClientSignatureVerificationRequiredArgsForCall)]
	fake.getClientSignatureVerificationRequiredArgsForCall = append(fake.getClientSignatureVerificationRequiredArgsForCall, struct {
	}{})
	stub := fake.GetClientSignatureVerificationRequiredStub
	fakeReturns := fake.getClientSignatureVerificationRequiredReturns
	fake.recordInvocation("GetClientSignatureVerificationRequired", []interface{}{})
	fake.getClientSignatureVerificationRequiredMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFilterConfig) GetClientSignatureVerificationRequiredCallCount() int {
	fake.getClientSignatureVerificationRequiredMutex.RLock()
	defer fake.getClientSignatureVerificationRequiredMutex.RUnlock()
	return len(fake.getClientSignatureVerificationRequiredArgsForCall)
}

func (fake *FakeFilterConfig) GetClientSignatureVerificationRequiredCalls(stub func() bool) {
	fake.getClientSignatureVerificationRequiredMutex.Lock()
	defer fake.getClientSignatureVerificationRequiredMutex.Unlock()
	fake.GetClientSignatureVerificationRequiredStub = stub
}

func (fake *FakeFilterConfig) GetClientSignatureVerificationRequiredReturns(result1 bool) {
	fake.getClientSignatureVerificationRequiredMutex.Lock()
	defer fake.getClientSignatureVerificationRequiredMutex.Unlock()
	fake.GetClientSignatureVerificationRequiredStub = nil
	fake.getClientSignatureVerificationRequiredReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeFilterConfig) GetClientSignatureVerificationRequiredReturnsOnCall(i int, result1 bool) {
	fake.getClientSignatureVerificationRequiredMutex.Lock()
	defer fake.getClientSignatureVerificationRequiredMutex.Unlock()
	fake.GetClientSignatureVerificationRequiredStub = nil
	if fake.getClientSignatureVerificationRequiredReturnsOnCall == nil {
		fake.getClientSignatureVerificationRequiredReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.getClientSignatureVerificationRequiredReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeFilterConfig) GetRequestMaxBytes() uint64 {
	fake.getRequestMaxBytesMutex.Lock()
	ret, specificReturn := fake.getRequestMaxBytesReturnsOnCall[len(fake.getRequestMaxBytesArgsForCall)]
	fake.getRequestMaxBytesArgsForCall = append(fake.getRequestMaxBytesArgsForCall, struct {
	}{})
	stub := fake.GetRequestMaxBytesStub
	fakeReturns := fake.getRequestMaxBytesReturns
	fake.recordInvocation("GetRequestMaxBytes", []interface{}{})
	fake.getRequestMaxBytesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeFilterConfig) GetRequestMaxBytesCallCount() int {
	fake.getRequestMaxBytesMutex.RLock()
	defer fake.getRequestMaxBytesMutex.RUnlock()
	return len(fake.getRequestMaxBytesArgsForCall)
}

func (fake *FakeFilterConfig) GetRequestMaxBytesCalls(stub func() uint64) {
	fake.getRequestMaxBytesMutex.Lock()
	defer fake.getRequestMaxBytesMutex.Unlock()
	fake.GetRequestMaxBytesStub = stub
}

func (fake *FakeFilterConfig) GetRequestMaxBytesReturns(result1 uint64) {
	fake.getRequestMaxBytesMutex.Lock()
	defer fake.getRequestMaxBytesMutex.Unlock()
	fake.GetRequestMaxBytesStub = nil
	fake.getRequestMaxBytesReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeFilterConfig) GetRequestMaxBytesReturnsOnCall(i int, result1 uint64) {
	fake.getRequestMaxBytesMutex.Lock()
	defer fake.getRequestMaxBytesMutex.Unlock()
	fake.GetRequestMaxBytesStub = nil
	if fake.getRequestMaxBytesReturnsOnCall == nil {
		fake.getRequestMaxBytesReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.getRequestMaxBytesReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeFilterConfig) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFilterConfig) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ requestfilter.FilterConfig = new(FakeFilterConfig)
