// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-common/common/channelconfig"
	"github.com/hyperledger/fabric-x-orderer/node/assembler/synchronizer"
	"github.com/hyperledger/fabric-x-orderer/node/comm"
)

type FakeAssemblerSupport struct {
	BlockStub        func(uint64) *common.Block
	blockMutex       sync.RWMutex
	blockArgsForCall []struct {
		arg1 uint64
	}
	blockReturns struct {
		result1 *common.Block
	}
	blockReturnsOnCall map[int]struct {
		result1 *common.Block
	}
	ChannelIDStub        func() string
	channelIDMutex       sync.RWMutex
	channelIDArgsForCall []struct {
	}
	channelIDReturns struct {
		result1 string
	}
	channelIDReturnsOnCall map[int]struct {
		result1 string
	}
	ClientConfigStub        func() comm.ClientConfig
	clientConfigMutex       sync.RWMutex
	clientConfigArgsForCall []struct {
	}
	clientConfigReturns struct {
		result1 comm.ClientConfig
	}
	clientConfigReturnsOnCall map[int]struct {
		result1 comm.ClientConfig
	}
	HeightStub        func() uint64
	heightMutex       sync.RWMutex
	heightArgsForCall []struct {
	}
	heightReturns struct {
		result1 uint64
	}
	heightReturnsOnCall map[int]struct {
		result1 uint64
	}
	LastConfigBlockStub        func(*common.Block) (*common.Block, error)
	lastConfigBlockMutex       sync.RWMutex
	lastConfigBlockArgsForCall []struct {
		arg1 *common.Block
	}
	lastConfigBlockReturns struct {
		result1 *common.Block
		result2 error
	}
	lastConfigBlockReturnsOnCall map[int]struct {
		result1 *common.Block
		result2 error
	}
	SerializeStub        func() ([]byte, error)
	serializeMutex       sync.RWMutex
	serializeArgsForCall []struct {
	}
	serializeReturns struct {
		result1 []byte
		result2 error
	}
	serializeReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SharedConfigStub        func() channelconfig.Orderer
	sharedConfigMutex       sync.RWMutex
	sharedConfigArgsForCall []struct {
	}
	sharedConfigReturns struct {
		result1 channelconfig.Orderer
	}
	sharedConfigReturnsOnCall map[int]struct {
		result1 channelconfig.Orderer
	}
	SignStub        func([]byte) ([]byte, error)
	signMutex       sync.RWMutex
	signArgsForCall []struct {
		arg1 []byte
	}
	signReturns struct {
		result1 []byte
		result2 error
	}
	signReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	WriteBlockSyncStub        func(*common.Block)
	writeBlockSyncMutex       sync.RWMutex
	writeBlockSyncArgsForCall []struct {
		arg1 *common.Block
	}
	WriteConfigBlockStub        func(*common.Block)
	writeConfigBlockMutex       sync.RWMutex
	writeConfigBlockArgsForCall []struct {
		arg1 *common.Block
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAssemblerSupport) Block(arg1 uint64) *common.Block {
	fake.blockMutex.Lock()
	ret, specificReturn := fake.blockReturnsOnCall[len(fake.blockArgsForCall)]
	fake.blockArgsForCall = append(fake.blockArgsForCall, struct {
		arg1 uint64
	}{arg1})
	stub := fake.BlockStub
	fakeReturns := fake.blockReturns
	fake.recordInvocation("Block", []interface{}{arg1})
	fake.blockMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAssemblerSupport) BlockCallCount() int {
	fake.blockMutex.RLock()
	defer fake.blockMutex.RUnlock()
	return len(fake.blockArgsForCall)
}

func (fake *FakeAssemblerSupport) BlockCalls(stub func(uint64) *common.Block) {
	fake.blockMutex.Lock()
	defer fake.blockMutex.Unlock()
	fake.BlockStub = stub
}

func (fake *FakeAssemblerSupport) BlockArgsForCall(i int) uint64 {
	fake.blockMutex.RLock()
	defer fake.blockMutex.RUnlock()
	argsForCall := fake.blockArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAssemblerSupport) BlockReturns(result1 *common.Block) {
	fake.blockMutex.Lock()
	defer fake.blockMutex.Unlock()
	fake.BlockStub = nil
	fake.blockReturns = struct {
		result1 *common.Block
	}{result1}
}

func (fake *FakeAssemblerSupport) BlockReturnsOnCall(i int, result1 *common.Block) {
	fake.blockMutex.Lock()
	defer fake.blockMutex.Unlock()
	fake.BlockStub = nil
	if fake.blockReturnsOnCall == nil {
		fake.blockReturnsOnCall = make(map[int]struct {
			result1 *common.Block
		})
	}
	fake.blockReturnsOnCall[i] = struct {
		result1 *common.Block
	}{result1}
}

func (fake *FakeAssemblerSupport) ChannelID() string {
	fake.channelIDMutex.Lock()
	ret, specificReturn := fake.channelIDReturnsOnCall[len(fake.channelIDArgsForCall)]
	fake.channelIDArgsForCall = append(fake.channelIDArgsForCall, struct {
	}{})
	stub := fake.ChannelIDStub
	fakeReturns := fake.channelIDReturns
	fake.recordInvocation("ChannelID", []interface{}{})
	fake.channelIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAssemblerSupport) ChannelIDCallCount() int {
	fake.channelIDMutex.RLock()
	defer fake.channelIDMutex.RUnlock()
	return len(fake.channelIDArgsForCall)
}

func (fake *FakeAssemblerSupport) ChannelIDCalls(stub func() string) {
	fake.channelIDMutex.Lock()
	defer fake.channelIDMutex.Unlock()
	fake.ChannelIDStub = stub
}

func (fake *FakeAssemblerSupport) ChannelIDReturns(result1 string) {
	fake.channelIDMutex.Lock()
	defer fake.channelIDMutex.Unlock()
	fake.ChannelIDStub = nil
	fake.channelIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeAssemblerSupport) ChannelIDReturnsOnCall(i int, result1 string) {
	fake.channelIDMutex.Lock()
	defer fake.channelIDMutex.Unlock()
	fake.ChannelIDStub = nil
	if fake.channelIDReturnsOnCall == nil {
		fake.channelIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.channelIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeAssemblerSupport) ClientConfig() comm.ClientConfig {
	fake.clientConfigMutex.Lock()
	ret, specificReturn := fake.clientConfigReturnsOnCall[len(fake.clientConfigArgsForCall)]
	fake.clientConfigArgsForCall = append(fake.clientConfigArgsForCall, struct {
	}{})
	stub := fake.ClientConfigStub
	fakeReturns := fake.clientConfigReturns
	fake.recordInvocation("ClientConfig", []interface{}{})
	fake.clientConfigMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAssemblerSupport) ClientConfigCallCount() int {
	fake.clientConfigMutex.RLock()
	defer fake.clientConfigMutex.RUnlock()
	return len(fake.clientConfigArgsForCall)
}

func (fake *FakeAssemblerSupport) ClientConfigCalls(stub func() comm.ClientConfig) {
	fake.clientConfigMutex.Lock()
	defer fake.clientConfigMutex.Unlock()
	fake.ClientConfigStub = stub
}

func (fake *FakeAssemblerSupport) ClientConfigReturns(result1 comm.ClientConfig) {
	fake.clientConfigMutex.Lock()
	defer fake.clientConfigMutex.Unlock()
	fake.ClientConfigStub = nil
	fake.clientConfigReturns = struct {
		result1 comm.ClientConfig
	}{result1}
}

func (fake *FakeAssemblerSupport) ClientConfigReturnsOnCall(i int, result1 comm.ClientConfig) {
	fake.clientConfigMutex.Lock()
	defer fake.clientConfigMutex.Unlock()
	fake.ClientConfigStub = nil
	if fake.clientConfigReturnsOnCall == nil {
		fake.clientConfigReturnsOnCall = make(map[int]struct {
			result1 comm.ClientConfig
		})
	}
	fake.clientConfigReturnsOnCall[i] = struct {
		result1 comm.ClientConfig
	}{result1}
}

func (fake *FakeAssemblerSupport) Height() uint64 {
	fake.heightMutex.Lock()
	ret, specificReturn := fake.heightReturnsOnCall[len(fake.heightArgsForCall)]
	fake.heightArgsForCall = append(fake.heightArgsForCall, struct {
	}{})
	stub := fake.HeightStub
	fakeReturns := fake.heightReturns
	fake.recordInvocation("Height", []interface{}{})
	fake.heightMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAssemblerSupport) HeightCallCount() int {
	fake.heightMutex.RLock()
	defer fake.heightMutex.RUnlock()
	return len(fake.heightArgsForCall)
}

func (fake *FakeAssemblerSupport) HeightCalls(stub func() uint64) {
	fake.heightMutex.Lock()
	defer fake.heightMutex.Unlock()
	fake.HeightStub = stub
}

func (fake *FakeAssemblerSupport) HeightReturns(result1 uint64) {
	fake.heightMutex.Lock()
	defer fake.heightMutex.Unlock()
	fake.HeightStub = nil
	fake.heightReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeAssemblerSupport) HeightReturnsOnCall(i int, result1 uint64) {
	fake.heightMutex.Lock()
	defer fake.heightMutex.Unlock()
	fake.HeightStub = nil
	if fake.heightReturnsOnCall == nil {
		fake.heightReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.heightReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeAssemblerSupport) LastConfigBlock(arg1 *common.Block) (*common.Block, error) {
	fake.lastConfigBlockMutex.Lock()
	ret, specificReturn := fake.lastConfigBlockReturnsOnCall[len(fake.lastConfigBlockArgsForCall)]
	fake.lastConfigBlockArgsForCall = append(fake.lastConfigBlockArgsForCall, struct {
		arg1 *common.Block
	}{arg1})
	stub := fake.LastConfigBlockStub
	fakeReturns := fake.lastConfigBlockReturns
	fake.recordInvocation("LastConfigBlock", []interface{}{arg1})
	fake.lastConfigBlockMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAssemblerSupport) LastConfigBlockCallCount() int {
	fake.lastConfigBlockMutex.RLock()
	defer fake.lastConfigBlockMutex.RUnlock()
	return len(fake.lastConfigBlockArgsForCall)
}

func (fake *FakeAssemblerSupport) LastConfigBlockCalls(stub func(*common.Block) (*common.Block, error)) {
	fake.lastConfigBlockMutex.Lock()
	defer fake.lastConfigBlockMutex.Unlock()
	fake.LastConfigBlockStub = stub
}

func (fake *FakeAssemblerSupport) LastConfigBlockArgsForCall(i int) *common.Block {
	fake.lastConfigBlockMutex.RLock()
	defer fake.lastConfigBlockMutex.RUnlock()
	argsForCall := fake.lastConfigBlockArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAssemblerSupport) LastConfigBlockReturns(result1 *common.Block, result2 error) {
	fake.lastConfigBlockMutex.Lock()
	defer fake.lastConfigBlockMutex.Unlock()
	fake.LastConfigBlockStub = nil
	fake.lastConfigBlockReturns = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeAssemblerSupport) LastConfigBlockReturnsOnCall(i int, result1 *common.Block, result2 error) {
	fake.lastConfigBlockMutex.Lock()
	defer fake.lastConfigBlockMutex.Unlock()
	fake.LastConfigBlockStub = nil
	if fake.lastConfigBlockReturnsOnCall == nil {
		fake.lastConfigBlockReturnsOnCall = make(map[int]struct {
			result1 *common.Block
			result2 error
		})
	}
	fake.lastConfigBlockReturnsOnCall[i] = struct {
		result1 *common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeAssemblerSupport) Serialize() ([]byte, error) {
	fake.serializeMutex.Lock()
	ret, specificReturn := fake.serializeReturnsOnCall[len(fake.serializeArgsForCall)]
	fake.serializeArgsForCall = append(fake.serializeArgsForCall, struct {
	}{})
	stub := fake.SerializeStub
	fakeReturns := fake.serializeReturns
	fake.recordInvocation("Serialize", []interface{}{})
	fake.serializeMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAssemblerSupport) SerializeCallCount() int {
	fake.serializeMutex.RLock()
	defer fake.serializeMutex.RUnlock()
	return len(fake.serializeArgsForCall)
}

func (fake *FakeAssemblerSupport) SerializeCalls(stub func() ([]byte, error)) {
	fake.serializeMutex.Lock()
	defer fake.serializeMutex.Unlock()
	fake.SerializeStub = stub
}

func (fake *FakeAssemblerSupport) SerializeReturns(result1 []byte, result2 error) {
	fake.serializeMutex.Lock()
	defer fake.serializeMutex.Unlock()
	fake.SerializeStub = nil
	fake.serializeReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeAssemblerSupport) SerializeReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.serializeMutex.Lock()
	defer fake.serializeMutex.Unlock()
	fake.SerializeStub = nil
	if fake.serializeReturnsOnCall == nil {
		fake.serializeReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.serializeReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeAssemblerSupport) SharedConfig() channelconfig.Orderer {
	fake.sharedConfigMutex.Lock()
	ret, specificReturn := fake.sharedConfigReturnsOnCall[len(fake.sharedConfigArgsForCall)]
	fake.sharedConfigArgsForCall = append(fake.sharedConfigArgsForCall, struct {
	}{})
	stub := fake.SharedConfigStub
	fakeReturns := fake.sharedConfigReturns
	fake.recordInvocation("SharedConfig", []interface{}{})
	fake.sharedConfigMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAssemblerSupport) SharedConfigCallCount() int {
	fake.sharedConfigMutex.RLock()
	defer fake.sharedConfigMutex.RUnlock()
	return len(fake.sharedConfigArgsForCall)
}

func (fake *FakeAssemblerSupport) SharedConfigCalls(stub func() channelconfig.Orderer) {
	fake.sharedConfigMutex.Lock()
	defer fake.sharedConfigMutex.Unlock()
	fake.SharedConfigStub = stub
}

func (fake *FakeAssemblerSupport) SharedConfigReturns(result1 channelconfig.Orderer) {
	fake.sharedConfigMutex.Lock()
	defer fake.sharedConfigMutex.Unlock()
	fake.SharedConfigStub = nil
	fake.sharedConfigReturns = struct {
		result1 channelconfig.Orderer
	}{result1}
}

func (fake *FakeAssemblerSupport) SharedConfigReturnsOnCall(i int, result1 channelconfig.Orderer) {
	fake.sharedConfigMutex.Lock()
	defer fake.sharedConfigMutex.Unlock()
	fake.SharedConfigStub = nil
	if fake.sharedConfigReturnsOnCall == nil {
		fake.sharedConfigReturnsOnCall = make(map[int]struct {
			result1 channelconfig.Orderer
		})
	}
	fake.sharedConfigReturnsOnCall[i] = struct {
		result1 channelconfig.Orderer
	}{result1}
}

func (fake *FakeAssemblerSupport) Sign(arg1 []byte) ([]byte, error) {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.signMutex.Lock()
	ret, specificReturn := fake.signReturnsOnCall[len(fake.signArgsForCall)]
	fake.signArgsForCall = append(fake.signArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	stub := fake.SignStub
	fakeReturns := fake.signReturns
	fake.recordInvocation("Sign", []interface{}{arg1Copy})
	fake.signMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAssemblerSupport) SignCallCount() int {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	return len(fake.signArgsForCall)
}

func (fake *FakeAssemblerSupport) SignCalls(stub func([]byte) ([]byte, error)) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = stub
}

func (fake *FakeAssemblerSupport) SignArgsForCall(i int) []byte {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	argsForCall := fake.signArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAssemblerSupport) SignReturns(result1 []byte, result2 error) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = nil
	fake.signReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeAssemblerSupport) SignReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.signMutex.Lock()
	defer fake.signMutex.Unlock()
	fake.SignStub = nil
	if fake.signReturnsOnCall == nil {
		fake.signReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.signReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeAssemblerSupport) WriteBlockSync(arg1 *common.Block) {
	fake.writeBlockSyncMutex.Lock()
	fake.writeBlockSyncArgsForCall = append(fake.writeBlockSyncArgsForCall, struct {
		arg1 *common.Block
	}{arg1})
	stub := fake.WriteBlockSyncStub
	fake.recordInvocation("WriteBlockSync", []interface{}{arg1})
	fake.writeBlockSyncMutex.Unlock()
	if stub != nil {
		fake.WriteBlockSyncStub(arg1)
	}
}

func (fake *FakeAssemblerSupport) WriteBlockSyncCallCount() int {
	fake.writeBlockSyncMutex.RLock()
	defer fake.writeBlockSyncMutex.RUnlock()
	return len(fake.writeBlockSyncArgsForCall)
}

func (fake *FakeAssemblerSupport) WriteBlockSyncCalls(stub func(*common.Block)) {
	fake.writeBlockSyncMutex.Lock()
	defer fake.writeBlockSyncMutex.Unlock()
	fake.WriteBlockSyncStub = stub
}

func (fake *FakeAssemblerSupport) WriteBlockSyncArgsForCall(i int) *common.Block {
	fake.writeBlockSyncMutex.RLock()
	defer fake.writeBlockSyncMutex.RUnlock()
	argsForCall := fake.writeBlockSyncArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAssemblerSupport) WriteConfigBlock(arg1 *common.Block) {
	fake.writeConfigBlockMutex.Lock()
	fake.writeConfigBlockArgsForCall = append(fake.writeConfigBlockArgsForCall, struct {
		arg1 *common.Block
	}{arg1})
	stub := fake.WriteConfigBlockStub
	fake.recordInvocation("WriteConfigBlock", []interface{}{arg1})
	fake.writeConfigBlockMutex.Unlock()
	if stub != nil {
		fake.WriteConfigBlockStub(arg1)
	}
}

func (fake *FakeAssemblerSupport) WriteConfigBlockCallCount() int {
	fake.writeConfigBlockMutex.RLock()
	defer fake.writeConfigBlockMutex.RUnlock()
	return len(fake.writeConfigBlockArgsForCall)
}

func (fake *FakeAssemblerSupport) WriteConfigBlockCalls(stub func(*common.Block)) {
	fake.writeConfigBlockMutex.Lock()
	defer fake.writeConfigBlockMutex.Unlock()
	fake.WriteConfigBlockStub = stub
}

func (fake *FakeAssemblerSupport) WriteConfigBlockArgsForCall(i int) *common.Block {
	fake.writeConfigBlockMutex.RLock()
	defer fake.writeConfigBlockMutex.RUnlock()
	argsForCall := fake.writeConfigBlockArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAssemblerSupport) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAssemblerSupport) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ synchronizer.AssemblerSupport = new(FakeAssemblerSupport)
