// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-orderer/node/assembler/synchronizer"
)

type FakeGenesisFetcher struct {
	CloseStub        func()
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	GenesisByEndpointsStub        func() (map[string]*common.Block, error)
	genesisByEndpointsMutex       sync.RWMutex
	genesisByEndpointsArgsForCall []struct {
	}
	genesisByEndpointsReturns struct {
		result1 map[string]*common.Block
		result2 error
	}
	genesisByEndpointsReturnsOnCall map[int]struct {
		result1 map[string]*common.Block
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGenesisFetcher) Close() {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		fake.CloseStub()
	}
}

func (fake *FakeGenesisFetcher) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeGenesisFetcher) CloseCalls(stub func()) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeGenesisFetcher) GenesisByEndpoints() (map[string]*common.Block, error) {
	fake.genesisByEndpointsMutex.Lock()
	ret, specificReturn := fake.genesisByEndpointsReturnsOnCall[len(fake.genesisByEndpointsArgsForCall)]
	fake.genesisByEndpointsArgsForCall = append(fake.genesisByEndpointsArgsForCall, struct {
	}{})
	stub := fake.GenesisByEndpointsStub
	fakeReturns := fake.genesisByEndpointsReturns
	fake.recordInvocation("GenesisByEndpoints", []interface{}{})
	fake.genesisByEndpointsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGenesisFetcher) GenesisByEndpointsCallCount() int {
	fake.genesisByEndpointsMutex.RLock()
	defer fake.genesisByEndpointsMutex.RUnlock()
	return len(fake.genesisByEndpointsArgsForCall)
}

func (fake *FakeGenesisFetcher) GenesisByEndpointsCalls(stub func() (map[string]*common.Block, error)) {
	fake.genesisByEndpointsMutex.Lock()
	defer fake.genesisByEndpointsMutex.Unlock()
	fake.GenesisByEndpointsStub = stub
}

func (fake *FakeGenesisFetcher) GenesisByEndpointsReturns(result1 map[string]*common.Block, result2 error) {
	fake.genesisByEndpointsMutex.Lock()
	defer fake.genesisByEndpointsMutex.Unlock()
	fake.GenesisByEndpointsStub = nil
	fake.genesisByEndpointsReturns = struct {
		result1 map[string]*common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeGenesisFetcher) GenesisByEndpointsReturnsOnCall(i int, result1 map[string]*common.Block, result2 error) {
	fake.genesisByEndpointsMutex.Lock()
	defer fake.genesisByEndpointsMutex.Unlock()
	fake.GenesisByEndpointsStub = nil
	if fake.genesisByEndpointsReturnsOnCall == nil {
		fake.genesisByEndpointsReturnsOnCall = make(map[int]struct {
			result1 map[string]*common.Block
			result2 error
		})
	}
	fake.genesisByEndpointsReturnsOnCall[i] = struct {
		result1 map[string]*common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeGenesisFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGenesisFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ synchronizer.GenesisFetcher = new(FakeGenesisFetcher)
