# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

################################################################################
#
#    Arma Assembler Configuration Template
#
################################################################################

# PartyID a unique identifier for each Arma party, uint16, id>0
PartyID: 1

################################################################################
#
#   SECTION: General: same as in template, except:
#   - Assembler does not need signing key pair (under LocalMSPDir)
#
################################################################################
General:

################################################################################
#
#   SECTION: File Store: same as in template
#
################################################################################
FileStore:

################################################################################
#
#   SECTION: Role specific configuration: only `Assembler` key
#
################################################################################

# Assembler specific parameters
Assembler:
  PrefetchBufferMemoryBytes: 1073741824
  RestartLedgerScanTimeout: 5s
  PrefetchEvictionTtl: 1h
  PopWaitMonitorTimeout: 1s
  ReplicationChannelSize: 100
  BatchRequestsChannelSize: 1000
