// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/common/types"
)

type FakeBatchID struct {
	DigestStub        func() []byte
	digestMutex       sync.RWMutex
	digestArgsForCall []struct{}
	digestReturns     struct {
		result1 []byte
	}
	digestReturnsOnCall map[int]struct {
		result1 []byte
	}
	PrimaryStub        func() types.PartyID
	primaryMutex       sync.RWMutex
	primaryArgsForCall []struct{}
	primaryReturns     struct {
		result1 types.PartyID
	}
	primaryReturnsOnCall map[int]struct {
		result1 types.PartyID
	}
	SeqStub        func() types.BatchSequence
	seqMutex       sync.RWMutex
	seqArgsForCall []struct{}
	seqReturns     struct {
		result1 types.BatchSequence
	}
	seqReturnsOnCall map[int]struct {
		result1 types.BatchSequence
	}
	ShardStub        func() types.ShardID
	shardMutex       sync.RWMutex
	shardArgsForCall []struct{}
	shardReturns     struct {
		result1 types.ShardID
	}
	shardReturnsOnCall map[int]struct {
		result1 types.ShardID
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchID) Digest() []byte {
	fake.digestMutex.Lock()
	ret, specificReturn := fake.digestReturnsOnCall[len(fake.digestArgsForCall)]
	fake.digestArgsForCall = append(fake.digestArgsForCall, struct{}{})
	stub := fake.DigestStub
	fakeReturns := fake.digestReturns
	fake.recordInvocation("Digest", []interface{}{})
	fake.digestMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchID) DigestCallCount() int {
	fake.digestMutex.RLock()
	defer fake.digestMutex.RUnlock()
	return len(fake.digestArgsForCall)
}

func (fake *FakeBatchID) DigestCalls(stub func() []byte) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = stub
}

func (fake *FakeBatchID) DigestReturns(result1 []byte) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = nil
	fake.digestReturns = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeBatchID) DigestReturnsOnCall(i int, result1 []byte) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = nil
	if fake.digestReturnsOnCall == nil {
		fake.digestReturnsOnCall = make(map[int]struct {
			result1 []byte
		})
	}
	fake.digestReturnsOnCall[i] = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeBatchID) Primary() types.PartyID {
	fake.primaryMutex.Lock()
	ret, specificReturn := fake.primaryReturnsOnCall[len(fake.primaryArgsForCall)]
	fake.primaryArgsForCall = append(fake.primaryArgsForCall, struct{}{})
	stub := fake.PrimaryStub
	fakeReturns := fake.primaryReturns
	fake.recordInvocation("Primary", []interface{}{})
	fake.primaryMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchID) PrimaryCallCount() int {
	fake.primaryMutex.RLock()
	defer fake.primaryMutex.RUnlock()
	return len(fake.primaryArgsForCall)
}

func (fake *FakeBatchID) PrimaryCalls(stub func() types.PartyID) {
	fake.primaryMutex.Lock()
	defer fake.primaryMutex.Unlock()
	fake.PrimaryStub = stub
}

func (fake *FakeBatchID) PrimaryReturns(result1 types.PartyID) {
	fake.primaryMutex.Lock()
	defer fake.primaryMutex.Unlock()
	fake.PrimaryStub = nil
	fake.primaryReturns = struct {
		result1 types.PartyID
	}{result1}
}

func (fake *FakeBatchID) PrimaryReturnsOnCall(i int, result1 types.PartyID) {
	fake.primaryMutex.Lock()
	defer fake.primaryMutex.Unlock()
	fake.PrimaryStub = nil
	if fake.primaryReturnsOnCall == nil {
		fake.primaryReturnsOnCall = make(map[int]struct {
			result1 types.PartyID
		})
	}
	fake.primaryReturnsOnCall[i] = struct {
		result1 types.PartyID
	}{result1}
}

func (fake *FakeBatchID) Seq() types.BatchSequence {
	fake.seqMutex.Lock()
	ret, specificReturn := fake.seqReturnsOnCall[len(fake.seqArgsForCall)]
	fake.seqArgsForCall = append(fake.seqArgsForCall, struct{}{})
	stub := fake.SeqStub
	fakeReturns := fake.seqReturns
	fake.recordInvocation("Seq", []interface{}{})
	fake.seqMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchID) SeqCallCount() int {
	fake.seqMutex.RLock()
	defer fake.seqMutex.RUnlock()
	return len(fake.seqArgsForCall)
}

func (fake *FakeBatchID) SeqCalls(stub func() types.BatchSequence) {
	fake.seqMutex.Lock()
	defer fake.seqMutex.Unlock()
	fake.SeqStub = stub
}

func (fake *FakeBatchID) SeqReturns(result1 types.BatchSequence) {
	fake.seqMutex.Lock()
	defer fake.seqMutex.Unlock()
	fake.SeqStub = nil
	fake.seqReturns = struct {
		result1 types.BatchSequence
	}{result1}
}

func (fake *FakeBatchID) SeqReturnsOnCall(i int, result1 types.BatchSequence) {
	fake.seqMutex.Lock()
	defer fake.seqMutex.Unlock()
	fake.SeqStub = nil
	if fake.seqReturnsOnCall == nil {
		fake.seqReturnsOnCall = make(map[int]struct {
			result1 types.BatchSequence
		})
	}
	fake.seqReturnsOnCall[i] = struct {
		result1 types.BatchSequence
	}{result1}
}

func (fake *FakeBatchID) Shard() types.ShardID {
	fake.shardMutex.Lock()
	ret, specificReturn := fake.shardReturnsOnCall[len(fake.shardArgsForCall)]
	fake.shardArgsForCall = append(fake.shardArgsForCall, struct{}{})
	stub := fake.ShardStub
	fakeReturns := fake.shardReturns
	fake.recordInvocation("Shard", []interface{}{})
	fake.shardMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchID) ShardCallCount() int {
	fake.shardMutex.RLock()
	defer fake.shardMutex.RUnlock()
	return len(fake.shardArgsForCall)
}

func (fake *FakeBatchID) ShardCalls(stub func() types.ShardID) {
	fake.shardMutex.Lock()
	defer fake.shardMutex.Unlock()
	fake.ShardStub = stub
}

func (fake *FakeBatchID) ShardReturns(result1 types.ShardID) {
	fake.shardMutex.Lock()
	defer fake.shardMutex.Unlock()
	fake.ShardStub = nil
	fake.shardReturns = struct {
		result1 types.ShardID
	}{result1}
}

func (fake *FakeBatchID) ShardReturnsOnCall(i int, result1 types.ShardID) {
	fake.shardMutex.Lock()
	defer fake.shardMutex.Unlock()
	fake.ShardStub = nil
	if fake.shardReturnsOnCall == nil {
		fake.shardReturnsOnCall = make(map[int]struct {
			result1 types.ShardID
		})
	}
	fake.shardReturnsOnCall[i] = struct {
		result1 types.ShardID
	}{result1}
}

func (fake *FakeBatchID) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.digestMutex.RLock()
	defer fake.digestMutex.RUnlock()
	fake.primaryMutex.RLock()
	defer fake.primaryMutex.RUnlock()
	fake.seqMutex.RLock()
	defer fake.seqMutex.RUnlock()
	fake.shardMutex.RLock()
	defer fake.shardMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchID) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ types.BatchID = new(FakeBatchID)
