# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

PartyID: 4
General:
    ListenAddress: 127.0.0.1
    ListenPort: 60623
    TLS:
        Enabled: true
        PrivateKey: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/consenter/tls/key.pem
        Certificate: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/consenter/tls/tls-cert.pem
        RootCAs:
            - /var/dec-trust/crypto/ordererOrganizations/org4/tlsca/tlsca-cert.pem
        ClientAuthRequired: false
    Keepalive:
        ClientInterval: 1m0s
        ClientTimeout: 20s
        ServerInterval: 2h0m0s
        ServerTimeout: 20s
        ServerMinInterval: 1m0s
    Backoff:
        BaseDelay: 1s
        Multiplier: 1.6
        MaxDelay: 2m0s
    MaxRecvMsgSize: 104857600
    MaxSendMsgSize: 104857600
    Bootstrap:
        Method: block
        File: /var/dec-trust/bootstrap/bootstrap.block
    Cluster:
        SendBufferSize: 2000
        ClientCertificate: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/consenter/tls/tls-cert.pem
        ClientPrivateKey: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/consenter/tls/key.pem
    LocalMSPDir: /var/dec-trust/crypto/ordererOrganizations/org4/orderers/party4/consenter/msp
    LocalMSPID: OrdererOrg4
    LogSpec: info
    MetricsLogInterval: 0s
FileStore:
    Location: /var/dec-trust/production/orderer/store
Consensus:
    WALDir: /var/dec-trust/production/orderer/store/wal
