// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-lib-go/bccsp"
	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-common/common/channelconfig"
	"github.com/hyperledger/fabric-x-orderer/config/verify"
)

type FakeOrdererRules struct {
	ValidateNewConfigStub        func(*common.Envelope, bccsp.BCCSP) error
	validateNewConfigMutex       sync.RWMutex
	validateNewConfigArgsForCall []struct {
		arg1 *common.Envelope
		arg2 bccsp.BCCSP
	}
	validateNewConfigReturns struct {
		result1 error
	}
	validateNewConfigReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateTransitionStub        func(channelconfig.Resources, *common.Envelope, bccsp.BCCSP) error
	validateTransitionMutex       sync.RWMutex
	validateTransitionArgsForCall []struct {
		arg1 channelconfig.Resources
		arg2 *common.Envelope
		arg3 bccsp.BCCSP
	}
	validateTransitionReturns struct {
		result1 error
	}
	validateTransitionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOrdererRules) ValidateNewConfig(arg1 *common.Envelope, arg2 bccsp.BCCSP) error {
	fake.validateNewConfigMutex.Lock()
	ret, specificReturn := fake.validateNewConfigReturnsOnCall[len(fake.validateNewConfigArgsForCall)]
	fake.validateNewConfigArgsForCall = append(fake.validateNewConfigArgsForCall, struct {
		arg1 *common.Envelope
		arg2 bccsp.BCCSP
	}{arg1, arg2})
	stub := fake.ValidateNewConfigStub
	fakeReturns := fake.validateNewConfigReturns
	fake.recordInvocation("ValidateNewConfig", []interface{}{arg1, arg2})
	fake.validateNewConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeOrdererRules) ValidateNewConfigCallCount() int {
	fake.validateNewConfigMutex.RLock()
	defer fake.validateNewConfigMutex.RUnlock()
	return len(fake.validateNewConfigArgsForCall)
}

func (fake *FakeOrdererRules) ValidateNewConfigCalls(stub func(*common.Envelope, bccsp.BCCSP) error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = stub
}

func (fake *FakeOrdererRules) ValidateNewConfigArgsForCall(i int) (*common.Envelope, bccsp.BCCSP) {
	fake.validateNewConfigMutex.RLock()
	defer fake.validateNewConfigMutex.RUnlock()
	argsForCall := fake.validateNewConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOrdererRules) ValidateNewConfigReturns(result1 error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = nil
	fake.validateNewConfigReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeOrdererRules) ValidateNewConfigReturnsOnCall(i int, result1 error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = nil
	if fake.validateNewConfigReturnsOnCall == nil {
		fake.validateNewConfigReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateNewConfigReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeOrdererRules) ValidateTransition(arg1 channelconfig.Resources, arg2 *common.Envelope, arg3 bccsp.BCCSP) error {
	fake.validateTransitionMutex.Lock()
	ret, specificReturn := fake.validateTransitionReturnsOnCall[len(fake.validateTransitionArgsForCall)]
	fake.validateTransitionArgsForCall = append(fake.validateTransitionArgsForCall, struct {
		arg1 channelconfig.Resources
		arg2 *common.Envelope
		arg3 bccsp.BCCSP
	}{arg1, arg2, arg3})
	stub := fake.ValidateTransitionStub
	fakeReturns := fake.validateTransitionReturns
	fake.recordInvocation("ValidateTransition", []interface{}{arg1, arg2, arg3})
	fake.validateTransitionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeOrdererRules) ValidateTransitionCallCount() int {
	fake.validateTransitionMutex.RLock()
	defer fake.validateTransitionMutex.RUnlock()
	return len(fake.validateTransitionArgsForCall)
}

func (fake *FakeOrdererRules) ValidateTransitionCalls(stub func(channelconfig.Resources, *common.Envelope, bccsp.BCCSP) error) {
	fake.validateTransitionMutex.Lock()
	defer fake.validateTransitionMutex.Unlock()
	fake.ValidateTransitionStub = stub
}

func (fake *FakeOrdererRules) ValidateTransitionArgsForCall(i int) (channelconfig.Resources, *common.Envelope, bccsp.BCCSP) {
	fake.validateTransitionMutex.RLock()
	defer fake.validateTransitionMutex.RUnlock()
	argsForCall := fake.validateTransitionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeOrdererRules) ValidateTransitionReturns(result1 error) {
	fake.validateTransitionMutex.Lock()
	defer fake.validateTransitionMutex.Unlock()
	fake.ValidateTransitionStub = nil
	fake.validateTransitionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeOrdererRules) ValidateTransitionReturnsOnCall(i int, result1 error) {
	fake.validateTransitionMutex.Lock()
	defer fake.validateTransitionMutex.Unlock()
	fake.ValidateTransitionStub = nil
	if fake.validateTransitionReturnsOnCall == nil {
		fake.validateTransitionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateTransitionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeOrdererRules) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOrdererRules) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ verify.OrdererRules = new(FakeOrdererRules)
