// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/common/types"
	"github.com/hyperledger/fabric-x-orderer/node/batcher"
)

type FakeSigVerifier struct {
	VerifySignatureStub        func(types.PartyID, types.ShardID, []byte, []byte) error
	verifySignatureMutex       sync.RWMutex
	verifySignatureArgsForCall []struct {
		arg1 types.PartyID
		arg2 types.ShardID
		arg3 []byte
		arg4 []byte
	}
	verifySignatureReturns struct {
		result1 error
	}
	verifySignatureReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSigVerifier) VerifySignature(arg1 types.PartyID, arg2 types.ShardID, arg3 []byte, arg4 []byte) error {
	var arg3Copy []byte
	if arg3 != nil {
		arg3Copy = make([]byte, len(arg3))
		copy(arg3Copy, arg3)
	}
	var arg4Copy []byte
	if arg4 != nil {
		arg4Copy = make([]byte, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.verifySignatureMutex.Lock()
	ret, specificReturn := fake.verifySignatureReturnsOnCall[len(fake.verifySignatureArgsForCall)]
	fake.verifySignatureArgsForCall = append(fake.verifySignatureArgsForCall, struct {
		arg1 types.PartyID
		arg2 types.ShardID
		arg3 []byte
		arg4 []byte
	}{arg1, arg2, arg3Copy, arg4Copy})
	stub := fake.VerifySignatureStub
	fakeReturns := fake.verifySignatureReturns
	fake.recordInvocation("VerifySignature", []interface{}{arg1, arg2, arg3Copy, arg4Copy})
	fake.verifySignatureMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSigVerifier) VerifySignatureCallCount() int {
	fake.verifySignatureMutex.RLock()
	defer fake.verifySignatureMutex.RUnlock()
	return len(fake.verifySignatureArgsForCall)
}

func (fake *FakeSigVerifier) VerifySignatureCalls(stub func(types.PartyID, types.ShardID, []byte, []byte) error) {
	fake.verifySignatureMutex.Lock()
	defer fake.verifySignatureMutex.Unlock()
	fake.VerifySignatureStub = stub
}

func (fake *FakeSigVerifier) VerifySignatureArgsForCall(i int) (types.PartyID, types.ShardID, []byte, []byte) {
	fake.verifySignatureMutex.RLock()
	defer fake.verifySignatureMutex.RUnlock()
	argsForCall := fake.verifySignatureArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeSigVerifier) VerifySignatureReturns(result1 error) {
	fake.verifySignatureMutex.Lock()
	defer fake.verifySignatureMutex.Unlock()
	fake.VerifySignatureStub = nil
	fake.verifySignatureReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSigVerifier) VerifySignatureReturnsOnCall(i int, result1 error) {
	fake.verifySignatureMutex.Lock()
	defer fake.verifySignatureMutex.Unlock()
	fake.VerifySignatureStub = nil
	if fake.verifySignatureReturnsOnCall == nil {
		fake.verifySignatureReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifySignatureReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSigVerifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.verifySignatureMutex.RLock()
	defer fake.verifySignatureMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSigVerifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batcher.SigVerifier = new(FakeSigVerifier)
