// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.ibm.com/decentralized-trust-research/arma/core"
	"github.ibm.com/decentralized-trust-research/arma/node/batcher"
)

type FakeStateReplicator struct {
	ReplicateStateStub        func() <-chan *core.State
	replicateStateMutex       sync.RWMutex
	replicateStateArgsForCall []struct {
	}
	replicateStateReturns struct {
		result1 <-chan *core.State
	}
	replicateStateReturnsOnCall map[int]struct {
		result1 <-chan *core.State
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStateReplicator) ReplicateState() <-chan *core.State {
	fake.replicateStateMutex.Lock()
	ret, specificReturn := fake.replicateStateReturnsOnCall[len(fake.replicateStateArgsForCall)]
	fake.replicateStateArgsForCall = append(fake.replicateStateArgsForCall, struct {
	}{})
	stub := fake.ReplicateStateStub
	fakeReturns := fake.replicateStateReturns
	fake.recordInvocation("ReplicateState", []interface{}{})
	fake.replicateStateMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStateReplicator) ReplicateStateCallCount() int {
	fake.replicateStateMutex.RLock()
	defer fake.replicateStateMutex.RUnlock()
	return len(fake.replicateStateArgsForCall)
}

func (fake *FakeStateReplicator) ReplicateStateCalls(stub func() <-chan *core.State) {
	fake.replicateStateMutex.Lock()
	defer fake.replicateStateMutex.Unlock()
	fake.ReplicateStateStub = stub
}

func (fake *FakeStateReplicator) ReplicateStateReturns(result1 <-chan *core.State) {
	fake.replicateStateMutex.Lock()
	defer fake.replicateStateMutex.Unlock()
	fake.ReplicateStateStub = nil
	fake.replicateStateReturns = struct {
		result1 <-chan *core.State
	}{result1}
}

func (fake *FakeStateReplicator) ReplicateStateReturnsOnCall(i int, result1 <-chan *core.State) {
	fake.replicateStateMutex.Lock()
	defer fake.replicateStateMutex.Unlock()
	fake.ReplicateStateStub = nil
	if fake.replicateStateReturnsOnCall == nil {
		fake.replicateStateReturnsOnCall = make(map[int]struct {
			result1 <-chan *core.State
		})
	}
	fake.replicateStateReturnsOnCall[i] = struct {
		result1 <-chan *core.State
	}{result1}
}

func (fake *FakeStateReplicator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.replicateStateMutex.RLock()
	defer fake.replicateStateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStateReplicator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batcher.StateReplicator = new(FakeStateReplicator)
