// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger-labs/SmartBFT/pkg/types"
	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	typesa "github.com/hyperledger/fabric-x-orderer/common/types"
	"github.com/hyperledger/fabric-x-orderer/node/consensus"
	"github.com/hyperledger/fabric-x-orderer/node/consensus/state"
)

type FakeConfigApplier struct {
	ApplyConfigToStateStub        func(*state.State, *state.ConfigRequest) (*state.State, error)
	applyConfigToStateMutex       sync.RWMutex
	applyConfigToStateArgsForCall []struct {
		arg1 *state.State
		arg2 *state.ConfigRequest
	}
	applyConfigToStateReturns struct {
		result1 *state.State
		result2 error
	}
	applyConfigToStateReturnsOnCall map[int]struct {
		result1 *state.State
		result2 error
	}
	ExtractConfigFromConfigBlockStub        func(*common.Block, typesa.PartyID) ([]uint64, types.Configuration, error)
	extractConfigFromConfigBlockMutex       sync.RWMutex
	extractConfigFromConfigBlockArgsForCall []struct {
		arg1 *common.Block
		arg2 typesa.PartyID
	}
	extractConfigFromConfigBlockReturns struct {
		result1 []uint64
		result2 types.Configuration
		result3 error
	}
	extractConfigFromConfigBlockReturnsOnCall map[int]struct {
		result1 []uint64
		result2 types.Configuration
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigApplier) ApplyConfigToState(arg1 *state.State, arg2 *state.ConfigRequest) (*state.State, error) {
	fake.applyConfigToStateMutex.Lock()
	ret, specificReturn := fake.applyConfigToStateReturnsOnCall[len(fake.applyConfigToStateArgsForCall)]
	fake.applyConfigToStateArgsForCall = append(fake.applyConfigToStateArgsForCall, struct {
		arg1 *state.State
		arg2 *state.ConfigRequest
	}{arg1, arg2})
	stub := fake.ApplyConfigToStateStub
	fakeReturns := fake.applyConfigToStateReturns
	fake.recordInvocation("ApplyConfigToState", []interface{}{arg1, arg2})
	fake.applyConfigToStateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeConfigApplier) ApplyConfigToStateCallCount() int {
	fake.applyConfigToStateMutex.RLock()
	defer fake.applyConfigToStateMutex.RUnlock()
	return len(fake.applyConfigToStateArgsForCall)
}

func (fake *FakeConfigApplier) ApplyConfigToStateCalls(stub func(*state.State, *state.ConfigRequest) (*state.State, error)) {
	fake.applyConfigToStateMutex.Lock()
	defer fake.applyConfigToStateMutex.Unlock()
	fake.ApplyConfigToStateStub = stub
}

func (fake *FakeConfigApplier) ApplyConfigToStateArgsForCall(i int) (*state.State, *state.ConfigRequest) {
	fake.applyConfigToStateMutex.RLock()
	defer fake.applyConfigToStateMutex.RUnlock()
	argsForCall := fake.applyConfigToStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeConfigApplier) ApplyConfigToStateReturns(result1 *state.State, result2 error) {
	fake.applyConfigToStateMutex.Lock()
	defer fake.applyConfigToStateMutex.Unlock()
	fake.ApplyConfigToStateStub = nil
	fake.applyConfigToStateReturns = struct {
		result1 *state.State
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigApplier) ApplyConfigToStateReturnsOnCall(i int, result1 *state.State, result2 error) {
	fake.applyConfigToStateMutex.Lock()
	defer fake.applyConfigToStateMutex.Unlock()
	fake.ApplyConfigToStateStub = nil
	if fake.applyConfigToStateReturnsOnCall == nil {
		fake.applyConfigToStateReturnsOnCall = make(map[int]struct {
			result1 *state.State
			result2 error
		})
	}
	fake.applyConfigToStateReturnsOnCall[i] = struct {
		result1 *state.State
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigApplier) ExtractConfigFromConfigBlock(arg1 *common.Block, arg2 typesa.PartyID) ([]uint64, types.Configuration, error) {
	fake.extractConfigFromConfigBlockMutex.Lock()
	ret, specificReturn := fake.extractConfigFromConfigBlockReturnsOnCall[len(fake.extractConfigFromConfigBlockArgsForCall)]
	fake.extractConfigFromConfigBlockArgsForCall = append(fake.extractConfigFromConfigBlockArgsForCall, struct {
		arg1 *common.Block
		arg2 typesa.PartyID
	}{arg1, arg2})
	stub := fake.ExtractConfigFromConfigBlockStub
	fakeReturns := fake.extractConfigFromConfigBlockReturns
	fake.recordInvocation("ExtractConfigFromConfigBlock", []interface{}{arg1, arg2})
	fake.extractConfigFromConfigBlockMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeConfigApplier) ExtractConfigFromConfigBlockCallCount() int {
	fake.extractConfigFromConfigBlockMutex.RLock()
	defer fake.extractConfigFromConfigBlockMutex.RUnlock()
	return len(fake.extractConfigFromConfigBlockArgsForCall)
}

func (fake *FakeConfigApplier) ExtractConfigFromConfigBlockCalls(stub func(*common.Block, typesa.PartyID) ([]uint64, types.Configuration, error)) {
	fake.extractConfigFromConfigBlockMutex.Lock()
	defer fake.extractConfigFromConfigBlockMutex.Unlock()
	fake.ExtractConfigFromConfigBlockStub = stub
}

func (fake *FakeConfigApplier) ExtractConfigFromConfigBlockArgsForCall(i int) (*common.Block, typesa.PartyID) {
	fake.extractConfigFromConfigBlockMutex.RLock()
	defer fake.extractConfigFromConfigBlockMutex.RUnlock()
	argsForCall := fake.extractConfigFromConfigBlockArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeConfigApplier) ExtractConfigFromConfigBlockReturns(result1 []uint64, result2 types.Configuration, result3 error) {
	fake.extractConfigFromConfigBlockMutex.Lock()
	defer fake.extractConfigFromConfigBlockMutex.Unlock()
	fake.ExtractConfigFromConfigBlockStub = nil
	fake.extractConfigFromConfigBlockReturns = struct {
		result1 []uint64
		result2 types.Configuration
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeConfigApplier) ExtractConfigFromConfigBlockReturnsOnCall(i int, result1 []uint64, result2 types.Configuration, result3 error) {
	fake.extractConfigFromConfigBlockMutex.Lock()
	defer fake.extractConfigFromConfigBlockMutex.Unlock()
	fake.ExtractConfigFromConfigBlockStub = nil
	if fake.extractConfigFromConfigBlockReturnsOnCall == nil {
		fake.extractConfigFromConfigBlockReturnsOnCall = make(map[int]struct {
			result1 []uint64
			result2 types.Configuration
			result3 error
		})
	}
	fake.extractConfigFromConfigBlockReturnsOnCall[i] = struct {
		result1 []uint64
		result2 types.Configuration
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeConfigApplier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.applyConfigToStateMutex.RLock()
	defer fake.applyConfigToStateMutex.RUnlock()
	fake.extractConfigFromConfigBlockMutex.RLock()
	defer fake.extractConfigFromConfigBlockMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigApplier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ consensus.ConfigApplier = new(FakeConfigApplier)
