// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/node/consensus"
	"github.com/hyperledger/fabric-x-orderer/node/consensus/state"
)

type FakeConfigApplier struct {
	ApplyConfigToStateStub        func(*state.State, *state.ConfigRequest) (*state.State, error)
	applyConfigToStateMutex       sync.RWMutex
	applyConfigToStateArgsForCall []struct {
		arg1 *state.State
		arg2 *state.ConfigRequest
	}
	applyConfigToStateReturns struct {
		result1 *state.State
		result2 error
	}
	applyConfigToStateReturnsOnCall map[int]struct {
		result1 *state.State
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigApplier) ApplyConfigToState(arg1 *state.State, arg2 *state.ConfigRequest) (*state.State, error) {
	fake.applyConfigToStateMutex.Lock()
	ret, specificReturn := fake.applyConfigToStateReturnsOnCall[len(fake.applyConfigToStateArgsForCall)]
	fake.applyConfigToStateArgsForCall = append(fake.applyConfigToStateArgsForCall, struct {
		arg1 *state.State
		arg2 *state.ConfigRequest
	}{arg1, arg2})
	fake.recordInvocation("ApplyConfigToState", []interface{}{arg1, arg2})
	fake.applyConfigToStateMutex.Unlock()
	if fake.ApplyConfigToStateStub != nil {
		return fake.ApplyConfigToStateStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.applyConfigToStateReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeConfigApplier) ApplyConfigToStateCallCount() int {
	fake.applyConfigToStateMutex.RLock()
	defer fake.applyConfigToStateMutex.RUnlock()
	return len(fake.applyConfigToStateArgsForCall)
}

func (fake *FakeConfigApplier) ApplyConfigToStateCalls(stub func(*state.State, *state.ConfigRequest) (*state.State, error)) {
	fake.applyConfigToStateMutex.Lock()
	defer fake.applyConfigToStateMutex.Unlock()
	fake.ApplyConfigToStateStub = stub
}

func (fake *FakeConfigApplier) ApplyConfigToStateArgsForCall(i int) (*state.State, *state.ConfigRequest) {
	fake.applyConfigToStateMutex.RLock()
	defer fake.applyConfigToStateMutex.RUnlock()
	argsForCall := fake.applyConfigToStateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeConfigApplier) ApplyConfigToStateReturns(result1 *state.State, result2 error) {
	fake.applyConfigToStateMutex.Lock()
	defer fake.applyConfigToStateMutex.Unlock()
	fake.ApplyConfigToStateStub = nil
	fake.applyConfigToStateReturns = struct {
		result1 *state.State
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigApplier) ApplyConfigToStateReturnsOnCall(i int, result1 *state.State, result2 error) {
	fake.applyConfigToStateMutex.Lock()
	defer fake.applyConfigToStateMutex.Unlock()
	fake.ApplyConfigToStateStub = nil
	if fake.applyConfigToStateReturnsOnCall == nil {
		fake.applyConfigToStateReturnsOnCall = make(map[int]struct {
			result1 *state.State
			result2 error
		})
	}
	fake.applyConfigToStateReturnsOnCall[i] = struct {
		result1 *state.State
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigApplier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.applyConfigToStateMutex.RLock()
	defer fake.applyConfigToStateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigApplier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ consensus.ConfigApplier = new(FakeConfigApplier)
