#!/usr/bin/env bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
set -euo pipefail

PATH="bin:${PATH}"

# Top-level Kingpin help renders commands in registration order. The arma CLI
# currently registers node commands by ranging over a Go map, so `arma --help`
# can print those commands in a different order on different runs. Generated
# docs must be deterministic; otherwise `scripts/help_docs.sh check` can fail
# even when help text has not changed.
#
# This wrapper delegates multiline command-block parsing to a separate Perl
# script so that parser can be formatted, syntax-highlighted, and commented as
# Perl instead of being hidden inside a Bash string.
normalizeCommandOrder() {
  local order="$1"
  scripts/normalize_help_commands.pl "$order"
}

# Print help text for one command string (for example, `arma router`).
#
# All commands have trailing whitespace stripped because different formatters can
# otherwise create noisy diffs. Top-level commands also get command-order
# normalization because stale-doc checks compare exact generated output.
runHelp() {
  local command="$1"
  case "$command" in
    "arma")
      $command --help 2>&1 | sed -E 's/[[:space:]]+$//g' | normalizeCommandOrder "help router assembler batcher consensus"
      ;;
    "armageddon")
      $command --help 2>&1 | sed -E 's/[[:space:]]+$//g' | normalizeCommandOrder "help generate showtemplate version submit load receive createSharedConfigProto createBlock"
      ;;
    *)
      $command --help 2>&1 | sed -E 's/[[:space:]]+$//g'
      ;;
  esac
}

# Print the hand-written intro for one generated CLI reference page.
#
# These preambles used to live in wrapper files. They are short and tightly tied
# to this generator, so they live here now to avoid extra files under docs/.
preamble() {
  local command="$1"

  case "$command" in
    "arma")
      cat <<'EOF'
# arma

The `arma` command launches Arma ordering service nodes: router, batcher, consensus, and assembler.
EOF
      ;;
    "armageddon")
      cat <<'EOF'
# armageddon

The `armageddon` command generates Arma configuration material and supports orderer test/load workflows.
EOF
      ;;
    *)
      echo "unknown command: $command" >&2
      exit 1
      ;;
  esac
}

# Generate one full Markdown reference page.
#
# Arguments:
#   $1: output Markdown file
#   $2: top-level command name used to choose the page preamble
#   $@: command strings whose `--help` output becomes fenced Markdown blocks
#
# Page layout:
#   generated-file warning -> preamble -> repeated `## command` help blocks.
generateHelpText() {
  local DOC="$1"
  local command="$2"
  shift 2

  cat <<EOF > "$DOC"
<!---
 File generated by $(basename "$0"). DO NOT EDIT.
 Edit scripts/help_docs.sh to change generated content.
 --->

EOF
  preamble "$command" >> "$DOC"

  local code_delim='```'
  local commands=("$@")
  for x in "${commands[@]}" ; do
    cat <<EOD >> "$DOC"

## $x
$code_delim
$(runHelp "$x")
$code_delim

EOD
  done
}

# Check that a committed generated doc is current.
#
# This writes fresh output to a temporary file, diffs it against the committed
# doc, and exits non-zero when they differ. The Makefile linter target uses this
# to catch stale CLI docs without modifying the workspace.
checkHelpTextCurrent() {
  local doc="$1"
  shift

  local tempfile
  tempfile="$(mktemp -t "$(basename "$doc")".XXXXX)" || exit 1

  generateHelpText "$tempfile" "$@"
  if ! diff -u "$doc" "$tempfile"; then
    rm -f "$tempfile"
    echo "The command line help docs are out of date and need to be regenerated. Run scripts/help_docs.sh generate."
    exit 2
  fi
  rm -f "$tempfile"
}

# Dispatch one doc generation/check operation based on global `action`.
#
# `generate` overwrites the target doc. `check` only compares generated output
# with the committed doc. Any other action is rejected so typos do not silently
# run the wrong mode.
generateOrCheck() {
  if [[ "$action" == "generate" ]]; then
    generateHelpText "$@"
  elif [[ "$action" == "check" ]]; then
    checkHelpTextCurrent "$@"
  else
    echo "usage: $0 [generate|check]" >&2
    exit 1
  fi
}

# Default to generate so maintainers can run `scripts/help_docs.sh` manually to
# refresh docs. CI/linter uses `scripts/help_docs.sh check`.
action="${1:-generate}"

# Each commands array defines one generated page. First argument to
# generateOrCheck is target doc, second is top-level command/preamble key, and
# remaining entries are command strings rendered as help blocks.
commands=("arma" "arma router" "arma batcher" "arma consensus" "arma assembler")
generateOrCheck \
  docs/cli/arma.md \
  arma \
  "${commands[@]}"

commands=("armageddon" "armageddon generate" "armageddon showtemplate" "armageddon version" "armageddon submit" "armageddon load" "armageddon receive" "armageddon createSharedConfigProto" "armageddon createBlock")
generateOrCheck \
  docs/cli/armageddon.md \
  armageddon \
  "${commands[@]}"
