// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-orderer/node/consensus/configrequest"
)

type FakeConfigRequestValidator struct {
	ValidateConfigRequestStub        func(*common.Envelope) error
	validateConfigRequestMutex       sync.RWMutex
	validateConfigRequestArgsForCall []struct {
		arg1 *common.Envelope
	}
	validateConfigRequestReturns struct {
		result1 error
	}
	validateConfigRequestReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateNewConfigStub        func(*common.Envelope) error
	validateNewConfigMutex       sync.RWMutex
	validateNewConfigArgsForCall []struct {
		arg1 *common.Envelope
	}
	validateNewConfigReturns struct {
		result1 error
	}
	validateNewConfigReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigRequestValidator) ValidateConfigRequest(arg1 *common.Envelope) error {
	fake.validateConfigRequestMutex.Lock()
	ret, specificReturn := fake.validateConfigRequestReturnsOnCall[len(fake.validateConfigRequestArgsForCall)]
	fake.validateConfigRequestArgsForCall = append(fake.validateConfigRequestArgsForCall, struct {
		arg1 *common.Envelope
	}{arg1})
	stub := fake.ValidateConfigRequestStub
	fakeReturns := fake.validateConfigRequestReturns
	fake.recordInvocation("ValidateConfigRequest", []interface{}{arg1})
	fake.validateConfigRequestMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigRequestValidator) ValidateConfigRequestCallCount() int {
	fake.validateConfigRequestMutex.RLock()
	defer fake.validateConfigRequestMutex.RUnlock()
	return len(fake.validateConfigRequestArgsForCall)
}

func (fake *FakeConfigRequestValidator) ValidateConfigRequestCalls(stub func(*common.Envelope) error) {
	fake.validateConfigRequestMutex.Lock()
	defer fake.validateConfigRequestMutex.Unlock()
	fake.ValidateConfigRequestStub = stub
}

func (fake *FakeConfigRequestValidator) ValidateConfigRequestArgsForCall(i int) *common.Envelope {
	fake.validateConfigRequestMutex.RLock()
	defer fake.validateConfigRequestMutex.RUnlock()
	argsForCall := fake.validateConfigRequestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConfigRequestValidator) ValidateConfigRequestReturns(result1 error) {
	fake.validateConfigRequestMutex.Lock()
	defer fake.validateConfigRequestMutex.Unlock()
	fake.ValidateConfigRequestStub = nil
	fake.validateConfigRequestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfigRequestValidator) ValidateConfigRequestReturnsOnCall(i int, result1 error) {
	fake.validateConfigRequestMutex.Lock()
	defer fake.validateConfigRequestMutex.Unlock()
	fake.ValidateConfigRequestStub = nil
	if fake.validateConfigRequestReturnsOnCall == nil {
		fake.validateConfigRequestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateConfigRequestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfigRequestValidator) ValidateNewConfig(arg1 *common.Envelope) error {
	fake.validateNewConfigMutex.Lock()
	ret, specificReturn := fake.validateNewConfigReturnsOnCall[len(fake.validateNewConfigArgsForCall)]
	fake.validateNewConfigArgsForCall = append(fake.validateNewConfigArgsForCall, struct {
		arg1 *common.Envelope
	}{arg1})
	stub := fake.ValidateNewConfigStub
	fakeReturns := fake.validateNewConfigReturns
	fake.recordInvocation("ValidateNewConfig", []interface{}{arg1})
	fake.validateNewConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigRequestValidator) ValidateNewConfigCallCount() int {
	fake.validateNewConfigMutex.RLock()
	defer fake.validateNewConfigMutex.RUnlock()
	return len(fake.validateNewConfigArgsForCall)
}

func (fake *FakeConfigRequestValidator) ValidateNewConfigCalls(stub func(*common.Envelope) error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = stub
}

func (fake *FakeConfigRequestValidator) ValidateNewConfigArgsForCall(i int) *common.Envelope {
	fake.validateNewConfigMutex.RLock()
	defer fake.validateNewConfigMutex.RUnlock()
	argsForCall := fake.validateNewConfigArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConfigRequestValidator) ValidateNewConfigReturns(result1 error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = nil
	fake.validateNewConfigReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfigRequestValidator) ValidateNewConfigReturnsOnCall(i int, result1 error) {
	fake.validateNewConfigMutex.Lock()
	defer fake.validateNewConfigMutex.Unlock()
	fake.ValidateNewConfigStub = nil
	if fake.validateNewConfigReturnsOnCall == nil {
		fake.validateNewConfigReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateNewConfigReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfigRequestValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigRequestValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ configrequest.ConfigRequestValidator = new(FakeConfigRequestValidator)
