// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"arma/core"
	"sync"
)

type FakeBatch struct {
	DigestStub        func() []byte
	digestMutex       sync.RWMutex
	digestArgsForCall []struct {
	}
	digestReturns struct {
		result1 []byte
	}
	digestReturnsOnCall map[int]struct {
		result1 []byte
	}
	PartyStub        func() core.PartyID
	partyMutex       sync.RWMutex
	partyArgsForCall []struct {
	}
	partyReturns struct {
		result1 core.PartyID
	}
	partyReturnsOnCall map[int]struct {
		result1 core.PartyID
	}
	RequestsStub        func() core.BatchedRequests
	requestsMutex       sync.RWMutex
	requestsArgsForCall []struct {
	}
	requestsReturns struct {
		result1 core.BatchedRequests
	}
	requestsReturnsOnCall map[int]struct {
		result1 core.BatchedRequests
	}
	SeqStub        func() core.BatchSequence
	seqMutex       sync.RWMutex
	seqArgsForCall []struct {
	}
	seqReturns struct {
		result1 core.BatchSequence
	}
	seqReturnsOnCall map[int]struct {
		result1 core.BatchSequence
	}
	ShardStub        func() core.ShardID
	shardMutex       sync.RWMutex
	shardArgsForCall []struct {
	}
	shardReturns struct {
		result1 core.ShardID
	}
	shardReturnsOnCall map[int]struct {
		result1 core.ShardID
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatch) Digest() []byte {
	fake.digestMutex.Lock()
	ret, specificReturn := fake.digestReturnsOnCall[len(fake.digestArgsForCall)]
	fake.digestArgsForCall = append(fake.digestArgsForCall, struct {
	}{})
	fake.recordInvocation("Digest", []interface{}{})
	fake.digestMutex.Unlock()
	if fake.DigestStub != nil {
		return fake.DigestStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.digestReturns
	return fakeReturns.result1
}

func (fake *FakeBatch) DigestCallCount() int {
	fake.digestMutex.RLock()
	defer fake.digestMutex.RUnlock()
	return len(fake.digestArgsForCall)
}

func (fake *FakeBatch) DigestCalls(stub func() []byte) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = stub
}

func (fake *FakeBatch) DigestReturns(result1 []byte) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = nil
	fake.digestReturns = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeBatch) DigestReturnsOnCall(i int, result1 []byte) {
	fake.digestMutex.Lock()
	defer fake.digestMutex.Unlock()
	fake.DigestStub = nil
	if fake.digestReturnsOnCall == nil {
		fake.digestReturnsOnCall = make(map[int]struct {
			result1 []byte
		})
	}
	fake.digestReturnsOnCall[i] = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeBatch) Party() core.PartyID {
	fake.partyMutex.Lock()
	ret, specificReturn := fake.partyReturnsOnCall[len(fake.partyArgsForCall)]
	fake.partyArgsForCall = append(fake.partyArgsForCall, struct {
	}{})
	fake.recordInvocation("Party", []interface{}{})
	fake.partyMutex.Unlock()
	if fake.PartyStub != nil {
		return fake.PartyStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.partyReturns
	return fakeReturns.result1
}

func (fake *FakeBatch) PartyCallCount() int {
	fake.partyMutex.RLock()
	defer fake.partyMutex.RUnlock()
	return len(fake.partyArgsForCall)
}

func (fake *FakeBatch) PartyCalls(stub func() core.PartyID) {
	fake.partyMutex.Lock()
	defer fake.partyMutex.Unlock()
	fake.PartyStub = stub
}

func (fake *FakeBatch) PartyReturns(result1 core.PartyID) {
	fake.partyMutex.Lock()
	defer fake.partyMutex.Unlock()
	fake.PartyStub = nil
	fake.partyReturns = struct {
		result1 core.PartyID
	}{result1}
}

func (fake *FakeBatch) PartyReturnsOnCall(i int, result1 core.PartyID) {
	fake.partyMutex.Lock()
	defer fake.partyMutex.Unlock()
	fake.PartyStub = nil
	if fake.partyReturnsOnCall == nil {
		fake.partyReturnsOnCall = make(map[int]struct {
			result1 core.PartyID
		})
	}
	fake.partyReturnsOnCall[i] = struct {
		result1 core.PartyID
	}{result1}
}

func (fake *FakeBatch) Requests() core.BatchedRequests {
	fake.requestsMutex.Lock()
	ret, specificReturn := fake.requestsReturnsOnCall[len(fake.requestsArgsForCall)]
	fake.requestsArgsForCall = append(fake.requestsArgsForCall, struct {
	}{})
	fake.recordInvocation("Requests", []interface{}{})
	fake.requestsMutex.Unlock()
	if fake.RequestsStub != nil {
		return fake.RequestsStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.requestsReturns
	return fakeReturns.result1
}

func (fake *FakeBatch) RequestsCallCount() int {
	fake.requestsMutex.RLock()
	defer fake.requestsMutex.RUnlock()
	return len(fake.requestsArgsForCall)
}

func (fake *FakeBatch) RequestsCalls(stub func() core.BatchedRequests) {
	fake.requestsMutex.Lock()
	defer fake.requestsMutex.Unlock()
	fake.RequestsStub = stub
}

func (fake *FakeBatch) RequestsReturns(result1 core.BatchedRequests) {
	fake.requestsMutex.Lock()
	defer fake.requestsMutex.Unlock()
	fake.RequestsStub = nil
	fake.requestsReturns = struct {
		result1 core.BatchedRequests
	}{result1}
}

func (fake *FakeBatch) RequestsReturnsOnCall(i int, result1 core.BatchedRequests) {
	fake.requestsMutex.Lock()
	defer fake.requestsMutex.Unlock()
	fake.RequestsStub = nil
	if fake.requestsReturnsOnCall == nil {
		fake.requestsReturnsOnCall = make(map[int]struct {
			result1 core.BatchedRequests
		})
	}
	fake.requestsReturnsOnCall[i] = struct {
		result1 core.BatchedRequests
	}{result1}
}

func (fake *FakeBatch) Seq() core.BatchSequence {
	fake.seqMutex.Lock()
	ret, specificReturn := fake.seqReturnsOnCall[len(fake.seqArgsForCall)]
	fake.seqArgsForCall = append(fake.seqArgsForCall, struct {
	}{})
	fake.recordInvocation("Seq", []interface{}{})
	fake.seqMutex.Unlock()
	if fake.SeqStub != nil {
		return fake.SeqStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.seqReturns
	return fakeReturns.result1
}

func (fake *FakeBatch) SeqCallCount() int {
	fake.seqMutex.RLock()
	defer fake.seqMutex.RUnlock()
	return len(fake.seqArgsForCall)
}

func (fake *FakeBatch) SeqCalls(stub func() core.BatchSequence) {
	fake.seqMutex.Lock()
	defer fake.seqMutex.Unlock()
	fake.SeqStub = stub
}

func (fake *FakeBatch) SeqReturns(result1 core.BatchSequence) {
	fake.seqMutex.Lock()
	defer fake.seqMutex.Unlock()
	fake.SeqStub = nil
	fake.seqReturns = struct {
		result1 core.BatchSequence
	}{result1}
}

func (fake *FakeBatch) SeqReturnsOnCall(i int, result1 core.BatchSequence) {
	fake.seqMutex.Lock()
	defer fake.seqMutex.Unlock()
	fake.SeqStub = nil
	if fake.seqReturnsOnCall == nil {
		fake.seqReturnsOnCall = make(map[int]struct {
			result1 core.BatchSequence
		})
	}
	fake.seqReturnsOnCall[i] = struct {
		result1 core.BatchSequence
	}{result1}
}

func (fake *FakeBatch) Shard() core.ShardID {
	fake.shardMutex.Lock()
	ret, specificReturn := fake.shardReturnsOnCall[len(fake.shardArgsForCall)]
	fake.shardArgsForCall = append(fake.shardArgsForCall, struct {
	}{})
	fake.recordInvocation("Shard", []interface{}{})
	fake.shardMutex.Unlock()
	if fake.ShardStub != nil {
		return fake.ShardStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.shardReturns
	return fakeReturns.result1
}

func (fake *FakeBatch) ShardCallCount() int {
	fake.shardMutex.RLock()
	defer fake.shardMutex.RUnlock()
	return len(fake.shardArgsForCall)
}

func (fake *FakeBatch) ShardCalls(stub func() core.ShardID) {
	fake.shardMutex.Lock()
	defer fake.shardMutex.Unlock()
	fake.ShardStub = stub
}

func (fake *FakeBatch) ShardReturns(result1 core.ShardID) {
	fake.shardMutex.Lock()
	defer fake.shardMutex.Unlock()
	fake.ShardStub = nil
	fake.shardReturns = struct {
		result1 core.ShardID
	}{result1}
}

func (fake *FakeBatch) ShardReturnsOnCall(i int, result1 core.ShardID) {
	fake.shardMutex.Lock()
	defer fake.shardMutex.Unlock()
	fake.ShardStub = nil
	if fake.shardReturnsOnCall == nil {
		fake.shardReturnsOnCall = make(map[int]struct {
			result1 core.ShardID
		})
	}
	fake.shardReturnsOnCall[i] = struct {
		result1 core.ShardID
	}{result1}
}

func (fake *FakeBatch) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.digestMutex.RLock()
	defer fake.digestMutex.RUnlock()
	fake.partyMutex.RLock()
	defer fake.partyMutex.RUnlock()
	fake.requestsMutex.RLock()
	defer fake.requestsMutex.RUnlock()
	fake.seqMutex.RLock()
	defer fake.seqMutex.RUnlock()
	fake.shardMutex.RLock()
	defer fake.shardMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatch) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ core.Batch = new(FakeBatch)
