# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: Verify Build
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

env:
  GOPATH: /opt/go
  PATH: /opt/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  basic-checks:
    name: Basic Checks
    runs-on: ${{ github.repository == 'hyperledger/fabric-x-orderer' && 'ubuntu-24.04' }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout Fabric-X Code
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        name: Install Go
        with:
          go-version-file: go.mod
      - run: go install golang.org/x/tools/cmd/goimports@latest
        name: Install goimports
      - run: go install mvdan.cc/gofumpt@latest
        name: Install gofumpt
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
        name: Install staticcheck
      - run: go install github.com/golang/protobuf/protoc-gen-go@latest
        name: Install protoc-gen-go
      - run: make basic-checks
        name: Run Basic Checks
